name: Run performance benchmarking

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Run performance benchmarking tests."
        required: false

jobs:
  timeout-minutes: 30
  steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4 
      with:
        python-version: 'pypy3.9'
    - name: Install tox
      run: pip install tox
    - name: Performance Benchmark
      env: 
        TOX_PARALLEL_NO_SPINNER: 1
      run:
        tox -e benchmark