name: Performance benchmark

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Run performance benchmarking tests."
        required: false

jobs:
  backend:
    timeout-minutes: 30
    
    strategy:
      matrix:
        python-versions: ['3.9']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Performance Benchmark
        run: |
          pip install git+https://git@github.com/Avaiga/taipy.git@develop scikit-learn
          python performance/main.py