name: Performance benchmark

on:
  workflow_dispatch:
    inputs:
      commitSHA:
        description: "The SHA value of the commit that triggered this action"
        required: true
        default: "5f58153d857a66f3cf7c0f6c84e7b6ca1984a0f2"
      repo:
        description: "The Taipy repo that called this action"
        required: true
        default: "taipy-core"


# OIDC token for the service principal
permissions:
  id-token: write
  contents: read


jobs:
  start-the-runner:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: actions/checkout@v3

      - name: Start the self-hosted runner
        run: az vm start -g github-runner -n integration-testing-runner

  backend:
    needs: start-the-runner
    timeout-minutes: 30
    
    strategy:
      matrix:
        python-versions: ['3.9']
        os: [ubuntu-latest]
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Performance Benchmark
        run: |
          python -m venv ./taipy-perf-env
          source taipy-perf-env/bin/activate
          pip install git+https://git@github.com/Avaiga/taipy.git@develop scikit-learn azure-storage-blob azure-identity
          pip install "git+https://git@github.com/Avaiga/taipy-core.git@$github.event.inputs.commitSha"
          export TAIPY_PERFORMANCE_BENCHMARK=0
          export AZURE_STORAGE_ACCOUNT_URL="${{secrets.AZURE_STORAGE_ACCOUNT_URL}}"
          export AZURE_CONTAINER_NAME="${{secrets.AZURE_CONTAINER_NAME}}"
          python performance/main.py --github-sha "${{github.event.inputs.commitSha}}" --repo "${{github.event.inputs.repo}}"
          deactivate

  stop-the-runner:
    needs: backend
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: actions/checkout@v3

      - name: Start the self-hosted runner
        run: az vm stop -g github-runner -n integration-testing-runner
        