

name: Python tests

on:
  pull_request:
    branches: [ develop ]

jobs:
  backend:
    timeout-minutes: 30
    strategy:
      matrix:
        python-versions: ['3.8', '3.11']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install Dependencies
        run: |
          pip install git+https://git@github.com/Avaiga/taipy.git@develop statsmodels Flask-Testing pytest scikit-learn mongomock

      - name: Tests
        run: |
          pytest
