name: Tests triggered from taipy PR

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository triggered from'
        required: true
        default: 'taipy'
      commitSHA:
        description: 'Commit SHA triggered for (default will be develop branch to avoid error)'
        required: true
        default: 'develop'

jobs:
  tests:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.11']
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Taipy from commit hash
        run: pip install "git+https://git@github.com/Avaiga/taipy.git@${{ github.event.inputs.commitSHA }}" statsmodels Flask-Testing pytest scikit-learn
      - name: Pytest test
        run: pytest tests
