

name: Python tests

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  backend:
    timeout-minutes: 30
    strategy:
      matrix:
        python-versions: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install mongomock
        run: pip install mongomock
      - name: Tests
        run: |
          pip install statsmodels Flask-Testing pytest scikit-learn
          pip install git+https://git@github.com/Avaiga/taipy.git@develop
          pip install git+https://${{ secrets.SSH_PRIVATE_KEY }}@github.com/Avaiga/taipy-auth
          pip install git+https://${{ secrets.SSH_PRIVATE_KEY }}@github.com/Avaiga/taipy-enterprise --no-dependencies

          pytest tests
