name: Python tests

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository triggered from'
        required: true
        default: 'taipy-core'
      commitSHA:
        description: 'Commit SHA triggered for (default will be develop branch to avoid error)'
        required: true
        default: 'develop'

jobs:
  backend:
    timeout-minutes: 30
    strategy:
      matrix:
        python-versions: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install Taipy
        run: pip install git+https://git@github.com/Avaiga/taipy.git@develop
      - name: Install Taipy Core From commit hash
        run: pip install "git+https://git@github.com/Avaiga/taipy-core.git@${{ github.event.inputs.commitSHA }}"
      - name: Install Test Dependencies
        run: pip install statsmodels Flask-Testing pytest scikit-learn schedule
      - name: Tests
        run: |
          pytest tests
