name: Python tests

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository triggered from'
        required: true
        default: 'taipy-core'
      commitSHA:
        description: 'Commit SHA triggered for (default will be develop branch to avoid error)'
        required: true
        default: 'develop'

jobs:
  churn_classification:
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ['3.8', '3.11']
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Taipy from commit hash
        run: pip install "git+https://git@github.com/Avaiga/taipy.git@develop"
      - name: Pytest churn_classification
        run: pytest -m "churn_classification" tests

  complex_application:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.11']
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Taipy from commit hash
        run: pip install "git+https://git@github.com/Avaiga/taipy.git@develop"
      - name: Pytest complex_application
        run: pytest -m "complex_application" tests

  skipped:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.11']
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Taipy from commit hash
        run: pip install "git+https://git@github.com/Avaiga/taipy.git@develop"
      - name: Pytest skipped
        run: pytest -m "skipped" tests

  tests:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.11']
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Taipy from commit hash
        run: pip install "git+https://git@github.com/Avaiga/taipy.git@develop"
      - name: Pytest test
        run: pytest -m "not churn_classification and not complex_application and not skipped" tests
