

name: Python tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  backend:
    timeout-minutes: 20
    strategy:
      matrix:
        python-versions: ['3.10']
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Tests
        run: |
          pip install git+https://git@github.com/Avaiga/taipy.git@develop statsmodels pytest
          pytest tests