name: Python tests

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository triggered from'
        required: true
        default: 'taipy-core'
      commitSHA:
        description: 'Commit SHA triggered for (default will be develop branch to avoid error)'
        required: true
        default: 'develop'

jobs:
  backend:
    timeout-minutes: 30
    strategy:
      matrix:
        python-versions: ['3.11']
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
      - name: Install mongomock
        run: pip install mongomock
      - name: Tests
        run: |
          pip install statsmodels Flask-Testing pytest scikit-learn
          pip install git+https://git@github.com/Avaiga/taipy.git@develop
          pip install git+https://${{ secrets.CLONE_PRIVATE_REPOSITORY }}@github.com/Avaiga/taipy-auth
          pip install git+https://${{ secrets.CLONE_PRIVATE_REPOSITORY }}@github.com/Avaiga/taipy-enterprise --no-dependencies
          pip install "git+https://git@github.com/Avaiga/taipy-core.git@${{ github.event.inputs.commitSHA }}"

          pytest tests
